### PR TITLE
Fixed bug in 'Custom Servers' section

### PR DESCRIPTION
**Pull request by robfors**

### CODE REVIEW

**Comment by ioquatix** [comment]
What was the bug?

**Comment by robfors** [comment]
The first issue I found was `MyServer.run` needs to be `MyServer.new.run`.

Then I tried to run
```
class MyServer < Async::DNS::Server
	def process(name, resource_class, transaction)
		transaction.fail!(:NXDomain)
	end
end

Async::Reactor.run do
	task = MyServer.run
	task.stop
end
```
with little success. I tried to `sleep` and such but it would not work. Then found that I could just remove `task.stop` it worked. So I backtraced my commit

**Comment by ioquatix** [comment]
I see. Thanks for your PR.

Let me clear some things up for you.

Imagine that the flow control inside the reactor block is linear and non-blocking. If you start the server and then call stop, it will stop immediately.

That's the expected behaviour.

If you want to wait on the server to finish, you can do the following:

- If you want to be explicit, you can call `task.wait`. But as it's a server it would never stop in this case, unless it crash or some other problem.

- If you actually want to sleep indefinitely, call `Async::Reactor.run do |task|; ... task.sleep`.

Async works like normal flow control as much as possible. But there are some limitations due to MRI/Ruby. (e.g. `sleep` vs `task.sleep`).

For the vast majority of servers, all you need to do is use `Async::Reactor.run do; MyServer.new.run; end` the example simply shows how you can shut down the server by calling stop, but perhaps that line should be removed/commented out because it's not typical flow control in a server (except perhaps in tests/specs).

**Comment by ioquatix** [comment]
After thinking about what you said, I updated README a bit more to clarify when to use `task.stop`. Thanks so much for taking the time to help the project :)

**Comment by robfors** [comment]
Thanks for the help. `Async` seems pretty cool once you understand it.

**Comment by ioquatix** [comment]
Thanks I appreciate your enthusiasm. The first commit to RubyDNS was in 2009, so it's been an interesting journey, `async`/`async-dns` and a few other bits were the end result.

**Pull request merged**
